#!/bin/sh
#
# @name Quad-Balloon Control
# @type Quadrotor +
# @class Copter
#
# @maintainer LareinaWei <lareinawei@gmail.com>
# @output Motor1 (Thrust only)
# @output Motor2 (Thrust only)
# @output Motor3 (Pitch + Yaw)
# @output Motor4 (Pitch - Yaw)
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MAV_TYPE 2

param set-default CA_ENABLE 1

param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX  0.2
param set-default CA_ROTOR0_PY  0.2
param set-default CA_ROTOR0_CT  1.0

param set-default CA_ROTOR1_PX -0.2
param set-default CA_ROTOR1_PY -0.2
param set-default CA_ROTOR1_CT  1.0

param set-default CA_ROTOR2_PX  0.2
param set-default CA_ROTOR2_PY -0.2
param set-default CA_ROTOR2_CT  0.0
param set-default CA_ROTOR2_TRQ_Y  0.1
param set-default CA_ROTOR2_TRQ_P  0.1
param set-default CA_ROTOR3_PX -0.2
param set-default CA_ROTOR3_PY  0.2
param set-default CA_ROTOR3_CT  0.0
param set-default CA_ROTOR3_TRQ_Y -0.1
param set-default CA_ROTOR3_TRQ_P -0.1

param set-default PWM_MAIN_FUNC1  Motor1
param set-default PWM_MAIN_FUNC2  Motor2
param set-default PWM_MAIN_FUNC3  Motor3
param set-default PWM_MAIN_FUNC4  Motor4

param set-default PWM_MAIN_REV1_MASK 15
param set-default PWM_MAIN_DISARMED 1500
param set-default PWM_MAIN_MIN 1000
param set-default PWM_MAIN_MAX 2000

param set-default CA_AIRFRAME 358762

param set-default MC_AIRMODE 1
